### ISSUE TITLE
missing adding required repository

### ISSUE THREAD

**Issue by ikke-t** [myllynen/satellite-automation#1]
The collection fails to install satellite as it doesn't add the required repository:

```
TASK [myllynen.satellite_automation.satellite_install : Enable Satellite module stream] *******************************************************************************
perjantai 30 syyskuu 2022  17:20:47 +0300 (0:00:01.766)       0:00:01.775 *****
fatal: [rh-satellite-01.cool.lab]: FAILED! => {"changed": true, "cmd": ["dnf", "-y", "module", "enable", "satellite:el8"], "delta": "0:00:06.402028", "end": "2022-09-30 17:20:54.561265", "msg": "non-zero return code", "rc": 1, "start": "2022-09-30 17:20:48.159237", "stderr": "Error: Problems in request:\nmissing groups or modules: satellite:el8", "stderr_lines": ["Error: Problems in request:", "missing groups or modules: satellite:el8"], "stdout": "Updating Subscription Management repositories.\nLast metadata expiration check: 0:28:47 ago on Fri Sep 30 16:52:04 2022.", "stdout_lines": ["Updating Subscription Management repositories.", "Last metadata expiration check: 0:28:47 ago on Fri Sep 30 16:52:04 2022."]}
```

**Comment by myllynen** [comment]
Yes, the README states that basics like networking, DNS, timesync, and repositories should be configured prior the Satellite setup, you could use the official RHEL system roles and my RHEL Ansible roles for these tasks. Particularly for repo setup I'd recommend this role:

https://github.com/myllynen/rhel-ansible-roles/tree/master/roles/repository_setup

The Satellite installation guide tells that in addition to baseos/appstream repos you'll need `satellite-6.11-for-rhel-8-x86_64-rpms` and `satellite-maintenance-6.11-for-rhel-8-x86_64-rpms`.

Thanks.
